spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://62.234.149.220:13306/blog?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 199748
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  resources:
    static-locations: file:/root/product-blog/static/

logging:
  level:
    root: warn
    com.yqj: debug
  file:
    name: log/blog-pro.log

server:
  port: 80
